---
title: "Figure 1 Data Summary"
author: "Sara Gosline"
date: "11/13/2020"
output: html_document
---

## Get Data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
library(amlresistancenetworks)

if(!exists('dataLoaded')){
  amlresistancenetworks::loadBeatAMLData()
  dataLoaded=TRUE
}

```

## Data Summary

The goal fo this markdown is to summarize the BeatAML data that we have so far. Patient summary, summary of AUC value, and general proteomics/protein data. 

```{r patient cohort}
  res<-auc.dat%>%select(-c('FLT3-ITD','FLT3-MUT','NPM1'))%>%
    plotAllAUCs(.,'AUC')

  full.drg<-res%>%
      tibble::rownames_to_column("AML sample")%>%
      left_join(auc.dat)%>%
      select(`AML sample`,Drug='Condition',proteins,RNA,mutations)%>%
    distinct()%>%
    group_by(Drug)%>%
    summarize(`Patients with proteomics`=length(which(proteins==TRUE)),`Patients with mRNA`=length(which(RNA==TRUE)),`Patients with Mutations`=length(which(mutations==TRUE)))
  
  knitr::kable(full.drg)
  write.csv(full.drg,'table1.csv')
  write.csv(res,'supp_table1.csv')
  
```

Since many of the patients are incomplete, we save a second version of the data that has only those 'complete' datasets.

```{r full patients}


red.auc<-auc.dat%>%subset(`AML sample`%in%full.pats$`AML sample`)
red.dat<-pat.data%>%subset(`AML sample`%in%full.pats$`AML sample`)
red.phos<-pat.phos%>%subset(Sample%in%full.pats$`AML sample`)

knitr::kable(res[full.pats$`AML sample`,])
```
