---
title: "Figure 3 Candidates signatures from LOO cross validation"
author: "Sara Gosline"
date: "11/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(amlresistancenetworks)
library(wesanderson)
pal<-wes_palette("Darjeeling1")
if(!exists('dataLoaded')){
  amlresistancenetworks::loadBeatAMLData()
  dataLoaded=TRUE
}

##assumes figure 2 was already generated!!!!
reg.preds<-readRDS('lassoRegPreds.rds')
log.preds<-readRDS('logRegPreds.rds')

```

## Best signatures from LASSO

From the predictions we can select those results that have the _best_ response, and plot those below. 

```{r lasso preds,warning=FALSE,echo=FALSE}


#'
#'selectDataMatAndPlot matches the output of a predictor (new.results) to the AUC data
#'and original molecular data to create heatmap
#'and combines ith with the specified data type and passes along a method to be used
#'@param drugName
#'@param meth
#'@param data
#'@return output of prediction
selectDataMatAndPlot<-function(drugName,method,data,genelist,doEnrich=FALSE){
 
  #get dimensionality-reduced samples
  if(data%in%c('proteinLevels','mRNALevels','geneMutations','binaryMutations') &&!is.null(pat.data))
    data.mat<-pat.data%>%dplyr::rename(value=data,Sample='AML sample')
  else if(data=='Latent Variable'&&!is.null(lv.df))
    data.mat<-lv.df%>%dplyr::rename(Gene='Latent_Variable',Sample='AML_sample',value='Loading')
  else if(data=='KinaseExpr'&&!is.null(pat.kin))
    data.mat<-pat.kin%>%dplyr::select(Gene='Kinase',Sample,value='meanLFC')
  else if(data=='Phosphosite'&&!is.null(pat.phos)){
    data.mat<-pat.phos%>%dplyr::select(Gene='site',Sample,value='LogFoldChange')
  }else if(data=='proteomicNetworkDistance'&&!is.null(prot.nets))
    data.mat<-prot.nets%>%dplyr::select(Gene='Community',value='distance',Sample=`AML sample`)
#  else if(data=='mutationNetworkDistances' && !is.null(mut.nets))
#    data.mat<-mut.nets%>%dplyr::select(Gene='Community',value='distance',Sample=`AML sample`)
  else{
    print(paste("Do not have data for",data))
    return(NULL)
  }
  
  auc.d<-auc.dat%>%
    dplyr::select(-c(medAUC,percAUC,overallSurvival,ageAtDiagnosis))%>%
    dplyr::rename(Sample='AML sample')

  genes=getFeaturesFromString(genelist,data)
  clusterSingleDrugEfficacy(drugName,method,data,doEnrich=doEnrich,
                              auc.dat=auc.d,auc.thresh=100,
                            genes,data.mat)  
}

  #reg.preds<<-reg.preds
  new.results<-reg.preds%>%subset(numFeatures>0)%>%subset(MSE<1500)%>%  
    mutate(method='LASSO',doEnrich=TRUE)%>%
    dplyr::rename(genelist='genes')%>%
   rowwise()%>%
    mutate(enrich=paste(selectDataMatAndPlot(var,method,Molecular,genelist,doEnrich)$Description,collapse=','))%>%
    rowwise()%>%
    mutate(features=paste(getFeaturesFromString(genelist,Molecular),collapse=','))%>%
    dplyr::select(Drug='var',MSE,features,dataType='Molecular',enrich)%>%
    arrange(MSE)

  
  knitr::kable(new.results)
```

## best signatures for logistic resgression

You can also embed plots, for example:

```{r logr preds, echo=FALSE, warning=FALSE}

  other.results<-log.preds%>%subset(numFeatures>2)%>%subset(MSE<0.21)%>%  
    mutate(method='LogisticRegression',doEnrich=TRUE)%>%
    dplyr::rename(genelist='genes')%>%
   rowwise()%>%
   mutate(enrich=paste(selectDataMatAndPlot(var,method,Molecular,genelist,doEnrich)$Description,collapse=','))%>%
    rowwise()%>%
    mutate(features=paste(getFeaturesFromString(genelist,Molecular),collapse=','))%>%
    dplyr::select(Drug='var',MSE,features,dataType='Molecular',enrich)%>%
  arrange(MSE)


knitr::kable(other.results)
full.results<-rbind(mutate(new.results,Model='LASSO'),
                    mutate(other.results,Model='Logistic'))

write.csv(full.results,'supp_table3_bestSigs.csv')

```


